In [1]:
from jax import numpy as jnp

In [2]:
l = [10, 20, 30, 12, 23, 34]
jnp.array(l)

Array([10, 20, 30, 12, 23, 34], dtype=int32)

In [4]:
jnp.empty(4)

Array([0., 0., 0., 0.], dtype=float32)

In [5]:
jnp.zeros([2, 3])

Array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [7]:
a = jnp.ones([2, 3, 4])
print(a.shape, a.dtype, a.size)
a

(2, 3, 4) float32 24


Array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [8]:
jnp.arange(10)

Array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [9]:
jnp.linspace(0, 1, 5)

Array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [10]:
list(jnp.linspace(0, 1, 5))

[Array(0., dtype=float32),
 Array(0.25, dtype=float32),
 Array(0.5, dtype=float32),
 Array(0.75, dtype=float32),
 Array(1., dtype=float32)]

In [13]:
import jax.random as jrandom

key = jrandom.PRNGKey(0)
A = jrandom.uniform(key, (4, 5))
print(A)

[[0.85417664 0.16620052 0.27605474 0.48728156 0.9920441 ]
 [0.03015983 0.21629429 0.37687123 0.63070035 0.96144474]
 [0.15203023 0.92090297 0.30555236 0.29931295 0.6925707 ]
 [0.8542826  0.46517384 0.7869307  0.99605286 0.28018546]]


In [14]:
A[:2, :3]

Array([[0.85417664, 0.16620052, 0.27605474],
       [0.03015983, 0.21629429, 0.37687123]], dtype=float32)

In [15]:
cond = A > 0.5
print(cond)
print(A[cond])

[[ True False False False  True]
 [False False False  True  True]
 [False  True False False  True]
 [ True False  True  True False]]
[0.85417664 0.9920441  0.63070035 0.96144474 0.92090297 0.6925707
 0.8542826  0.7869307  0.99605286]


In [16]:
(A + 5)**2

Array([[34.27138 , 26.689629, 27.836756, 30.110262, 35.90459 ],
       [25.30251 , 27.209726, 28.910744, 31.704784, 35.538826],
       [26.543413, 35.057095, 28.148888, 28.08272 , 32.40536 ],
       [34.27262 , 29.868124, 33.488564, 35.95265 , 27.880362]],      dtype=float32)

In [17]:
jnp.exp(A)

Array([[2.3494391, 1.1808099, 1.31792  , 1.6278849, 2.696741 ],
       [1.0306193, 1.2414677, 1.4577166, 1.878926 , 2.6154723],
       [1.1641954, 2.511557 , 1.3573745, 1.3489317, 1.9988474],
       [2.349688 , 1.592291 , 2.1966438, 2.7075734, 1.3233752]],      dtype=float32)

In [20]:
A = A.at[:, 0].set(0)
print(A)

[[0.         0.16620052 0.27605474 0.48728156 0.9920441 ]
 [0.         0.21629429 0.37687123 0.63070035 0.96144474]
 [0.         0.92090297 0.30555236 0.29931295 0.6925707 ]
 [0.         0.46517384 0.7869307  0.99605286 0.28018546]]


In [21]:
cond = (A != 0)
A = A.at[cond].set(1/A[cond])
print(A)

[[0.        6.0168285 3.62247   2.0522015 1.0080197]
 [0.        4.6233306 2.6534262 1.585539  1.0401014]
 [0.        1.0858908 3.2727613 3.3409848 1.4438959]
 [0.        2.149734  1.2707599 1.0039628 3.5690646]]


In [23]:
for i, v in enumerate( [s for s in dir(jnp) if not s.startswith('_')]):
    print(f"{i+1:16}. {v}")
    if (i+1) % 6 == 0:print("")

               1. ComplexWarning
               2. abs
               3. absolute
               4. acos
               5. acosh
               6. add

               7. all
               8. allclose
               9. amax
              10. amin
              11. angle
              12. any

              13. append
              14. apply_along_axis
              15. apply_over_axes
              16. arange
              17. arccos
              18. arccosh

              19. arcsin
              20. arcsinh
              21. arctan
              22. arctan2
              23. arctanh
              24. argmax

              25. argmin
              26. argpartition
              27. argsort
              28. argwhere
              29. around
              30. array

              31. array_equal
              32. array_equiv
              33. array_repr
              34. array_split
              35. array_str
              36. asarray

              37. asin
              38. asinh
 

In [24]:
print(A)
print(A.shape)
A_flatten = A.flatten()
print(A_flatten, A_flatten.shape)

[[0.        6.0168285 3.62247   2.0522015 1.0080197]
 [0.        4.6233306 2.6534262 1.585539  1.0401014]
 [0.        1.0858908 3.2727613 3.3409848 1.4438959]
 [0.        2.149734  1.2707599 1.0039628 3.5690646]]
(4, 5)
[0.        6.0168285 3.62247   2.0522015 1.0080197 0.        4.6233306
 2.6534262 1.585539  1.0401014 0.        1.0858908 3.2727613 3.3409848
 1.4438959 0.        2.149734  1.2707599 1.0039628 3.5690646] (20,)
